name: generate-documentation

on: [push]

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: "5"
        number of databases: 1
    - name: Set up as module
      run: |
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm install
        HERE=`pwd`
        npm version patch
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/storage-redis
        npm install -g mocha
        rm node_modules/@userdashboard/dashboard/*.js
        rm -rf node_modules/@userdashboard/dashboard/src
        rm -rf node_modules/@userdashboard/dashboard/languages
        cp /home/runner/work/dashboard/dashboard/*.js node_modules/@userdashboard/dashboard
        cp -R $HERE/src/ node_modules/@userdashboard/dashboard/src/
        cp -R $HERE/languages/ node_modules/@userdashboard/dashboard/languages/
        echo "global.applicationPath = __dirname" > main.js
    - name: Generate translations
      run: |
        git clone https://github.com/userdashboard/localization.git /tmp/localization
        cd /tmp/localization
        for LOCALE in `cat languages`; do
          node clean-cache.js "$LOCALE" "/home/runner/work/localization/localization/project/dashboard" "/home/runner/work/dashboard/dashboard"
          node localize.js "$LOCALE" "/home/runner/work/dashboard/dashboard"
        done
    - name: Generate documentation
      run: |
        mocha --grep returns --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
        mocha --grep screenshots --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-redis"
        REDIS_URL: "redis://localhost:6379"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false   
        GENERATE_RESPONSE: true
        GENERATE_SCREENSHOTS: true
        RESPONSE_PATH: "/home/runner/work/dashboard/dashboard/documentation"
        SCREENSHOT_PATH: "/home/runner/work/dashboard/dashboard/documentation/screenshots"
        SCREENSHOT_LANGUAGES: "en,es,af,bg,pl,tr,hu,vi"
        LOG_LEVEL: "info,error,warn,log"
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: "userdashboard/userdashboard.github.io"
        personal_token: ${{ secrets.DOCUMENTATION_PAT }}
        publish_dir: documentation
        publish_branch: master
        keep_files: true
